# -*- coding: utf-8 -*-
"""predict_yield

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NpA23k8u_hHl3Mn6smWNwZukVK2Qh8H3
"""

# predict_yield.py

import pickle
import numpy as np
import os
import gdown

# Google Drive model download
YIELD_MODEL_ID = "1QXq2c3Gl2SjK1dM7bIOCvXSxK0hbVXnS"
YIELD_MODEL_PATH = "app/models/crop_yield_model.pkl"

def download_yield_model():
    if not os.path.exists(YIELD_MODEL_PATH):
        url = f"https://drive.google.com/uc?id={YIELD_MODEL_ID}"
        os.makedirs(os.path.dirname(YIELD_MODEL_PATH), exist_ok=True)
        gdown.download(url, YIELD_MODEL_PATH, quiet=False)

def load_yield_model():
    download_yield_model()
    with open(YIELD_MODEL_PATH, 'rb') as f:
        return pickle.load(f)

def predict_yield(data: dict):
    model = load_yield_model()
    crop_map = {"Corn": 0, "Potato": 1, "Rice": 2, "Sugarcane": 3, "Wheat": 4}
    soil_map = {"Clay": 0, "Loamy": 1, "Peaty": 2, "Saline": 3, "Sandy": 4}

    input_array = np.array([[
        crop_map[data['crop_type']],
        soil_map[data['soil_type']],
        data['soil_ph'],
        data['temperature'],
        data['humidity'],
        data['wind_speed'],
        data['n'],
        data['p'],
        data['k'],
        data['soil_quality']
    ]])

    return model.predict(input_array)[0]