# -*- coding: utf-8 -*-
"""request_schemas.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NpA23k8u_hHl3Mn6smWNwZukVK2Qh8H3
"""

from pydantic import BaseModel
from typing import Optional

class YieldInput(BaseModel):
    crop_type: str
    soil_type: str
    soil_ph: float
    temperature: float
    humidity: float
    wind_speed: float
    n: float
    p: float
    k: float
    soil_quality: float

class Location(BaseModel):
    latitude: float
    longitude: float