# -*- coding: utf-8 -*-
"""geo_weather.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NpA23k8u_hHl3Mn6smWNwZukVK2Qh8H3
"""

from fastapi import APIRouter, Query, HTTPException
import requests
import os
from dotenv import load_dotenv

load_dotenv()

router = APIRouter()

OPENWEATHER_API = os.getenv("OPENWEATHER_API")

@router.get("/geo-weather")
def get_weather_data(lat: float = Query(...), lon: float = Query(...)):
    """
    Get environmental weather data from coordinates.
    Input: lat & lon
    Output: temperature, humidity, wind speed
    """

    if not OPENWEATHER_API:
        raise HTTPException(status_code=500, detail="OpenWeather API key not set.")

    url = (
        f"https://api.openweathermap.org/data/2.5/weather?"
        f"lat={lat}&lon={lon}&appid={OPENWEATHER_API}&units=metric"
    )

    try:
        response = requests.get(url)
        data = response.json()

        if response.status_code != 200:
            raise HTTPException(status_code=500, detail=data.get("message", "Failed to fetch weather"))

        temperature = data['main']['temp']
        humidity = data['main']['humidity']
        wind_speed = data['wind']['speed']

        return {
            "Temperature": temperature,
            "Humidity": humidity,
            "Wind_Speed": wind_speed,
            "message": "Environmental data fetched successfully"
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))