# -*- coding: utf-8 -*-
"""helper.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NpA23k8u_hHl3Mn6smWNwZukVK2Qh8H3
"""

import numpy as np

# Crop and soil mappings (same used in Streamlit)
CROP_TYPE_ENCODING = {
    "Corn": 0,
    "Potato": 1,
    "Rice": 2,
    "Sugarcane": 3,
    "Wheat": 4
}

SOIL_TYPE_ENCODING = {
    "Clay": 0,
    "Loamy": 1,
    "Peaty": 2,
    "Saline": 3,
    "Sandy": 4
}

def encode_input_data(data: dict):
    """
    Encode categorical features and convert to numpy array for model.
    Input: {
        "Crop_Type": "Corn",
        "Soil_Type": "Loamy",
        ...
    }
    Output: numpy array shape (1, 10)
    """

    try:
        crop = CROP_TYPE_ENCODING[data["Crop_Type"]]
        soil = SOIL_TYPE_ENCODING[data["Soil_Type"]]

        input_array = np.array([[
            crop,
            soil,
            float(data["Soil_pH"]),
            float(data["Temperature"]),
            float(data["Humidity"]),
            float(data["Wind_Speed"]),
            float(data["Nitrogen"]),
            float(data["Phosphorus"]),
            float(data["Potassium"]),
            float(data["Soil_Quality"])
        ]])

        return input_array

    except KeyError as e:
        raise ValueError(f"Invalid categorical value: {e}")

    except Exception as e:
        raise ValueError(f"Error encoding input data: {e}")