# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NpA23k8u_hHl3Mn6smWNwZukVK2Qh8H3
"""

from fastapi import FastAPI, UploadFile, File, HTTPException
from app.schemas.request_schemas import YieldInput, Location
from app.utils.predict_yield import predict_yield
from app.utils.predict_disease import predict_disease
import httpx
from dotenv import load_dotenv
import os

load_dotenv()

app = FastAPI()

@app.post("/predict-yield")
def yield_prediction(input_data: YieldInput):
    try:
        result = predict_yield(input_data.dict())
        return {"predicted_yield_tph": round(result, 2)}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/predict-disease-image")
def disease_prediction(image: UploadFile = File(...)):
    try:
        prediction = predict_disease(image.file)
        return {"disease_prediction_class": prediction}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/geo-weather")
def get_weather(location: Location):
    try:
        api_key = os.getenv("OPENWEATHER_API")
        lat, lon = location.latitude, location.longitude
        url = f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={api_key}&units=metric"
        response = httpx.get(url)
        data = response.json()
        return {
            "temperature": data['main']['temp'],
            "humidity": data['main']['humidity'],
            "wind_speed": data['wind']['speed']
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))